yatube/about/urls.py
# about/urls.py

from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py

from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main_page'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

yatube/users/urls.py
# users/urls.py

from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    # Личный кабинет
    path(
        'account/',
        views.accaunt,
        # views.AccountView.as_view(),
        name='account'
    ),
    # Авторизация
    path(
        'login/',
        views.LoginView.as_view(),
        name='login'
    ),
    # Выход
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='logout'
    ),
    # Регистрация
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    # Смена пароля
    path(
        'password_change/',
        views.PasswordChangeView.as_view(),
        name='password_change_form'
    ),
    # Сообщение об успешном изменении пароля
    path(
        'password_change/done/',
        views.PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),
    # Восстановление пароля
    path(
        'password_reset/',
        views.PasswordResetView.as_view(),
        name='password_reset_form'
    ),
    # Сообщение об отправке ссылки для восстановления пароля
    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    # Вход по ссылке для восстановления пароля
    path(
        'password_reset/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    # Сообщение об успешном восстановлении пароля
    path(
        'password_reset/complete/',
        views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
    path(
        'end_of_<str:username>/',
        views.kill_me_please,
        name='kmp'
    ),
]

yatube/yatube/urls.py
# noinspection GrazieInspection

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

# handler400 = 'core.views.bad_request'
handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    # path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/comment_frame.html
<div class="media mb-4">
  <div class="media-body">
    <ul class="list-inline list-group-horizontal">
      <li class="list-inline-item">
        <h5 class="mt-0 display:inline">
          <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author }}
          </a>
        </h5>
      </li>
      <li class="list-inline-item">
        <span class="display:inline">{{ comment.created|date:"d E Y" }}</span>
      </li>
    </ul>
    <p>
      {{ comment.text }}
    </p>
  </div>
</div>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>
    © 2022 - {{ year_now }} Copyright <span style="color:red">Ya</span>tube
  </p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    {% with request.resolver_match.view_name as view_name %}
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:main_page' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:password_change_form' %}active{% endif %} link-light" href="{% url 'users:password_change_form' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="nav-item">
          {% comment %} <a class="nav-link {% if view_name == 'users:account' %}active{% endif %} link-light" href="{% url 'users:account' %}">Пользователь: {{ user.username }}</a> {% endcomment %}
          <a class="nav-link {% if view_name == 'posts:profile' %}active{% endif %} link-light" href="{% url 'posts:profile' user.username %}">Пользователь: {{ user.username }}</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:login' %}active{% endif %} link-light" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:signup' %}active{% endif %} link-light" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
    {% endwith %}
  </nav>
</header>

yatube/templates/includes/paginator.html
<div class="d-flex justify-content-center">
  {% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active">
              <span class="page-link">{{ i }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
          {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>

yatube/templates/includes/post_frame.html
{% load thumbnail %}
<article>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-10 p-5">
        <div class="card">
          <div class="card-header">
            <ul>
              <li>
                Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
          </div>
          <div class="card-body">
            {% thumbnail post.image '600x200' crop="center" upscale=True as img %}
            <img class="card-img my-2" src="{{ img.url }}">
            {% endthumbnail %}
            <p class="card-text">
              {{ post.text }}
            </p>
            <hr>
            {% if post.group and not group %}
            <p>
              <a
              href="{% url 'posts:group_list' post.group.slug %}"
              >
                # Все записи группы "{{ post.group.title }}"
              </a>
            </p>
            {% endif %}
            <p>
              Комментариев: {{ post.comments.count }}
            </p>
            <br>
            <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:post_detail' post.pk %}"
            role="button"
            >
              Подробная информация
            </a>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div> <!-- container -->
</article>

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
{% with request.resolver_match.view_name as view_name %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if view_name == 'posts:main_page' %}active{% endif %}"
          href="{% url 'posts:main_page' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
          class="nav-link {% if view_name == 'posts:follow_index' %}active{% endif %}"
          href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endwith %}
{% endif %}