yatube/about/urls.py
# about/urls.py

from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py

from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main_page'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

yatube/users/urls.py
# users/urls.py

from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    # Личный кабинет
    path(
        'account/',
        views.accaunt,
        # views.AccountView.as_view(),
        name='account'
    ),
    # Авторизация
    path(
        'login/',
        views.LoginView.as_view(),
        name='login'
    ),
    # Выход
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='logout'
    ),
    # Регистрация
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    # Смена пароля
    path(
        'password_change/',
        views.PasswordChangeView.as_view(),
        name='password_change_form'
    ),
    # Сообщение об успешном изменении пароля
    path(
        'password_change/done/',
        views.PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),
    # Восстановление пароля
    path(
        'password_reset/',
        views.PasswordResetView.as_view(),
        name='password_reset_form'
    ),
    # Сообщение об отправке ссылки для восстановления пароля
    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    # Вход по ссылке для восстановления пароля
    path(
        'password_reset/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    # Сообщение об успешном восстановлении пароля
    path(
        'password_reset/complete/',
        views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
    path(
        'end_of_<str:username>/',
        views.kill_me_please,
        name='kmp'
    ),
]

yatube/yatube/urls.py
# noinspection GrazieInspection

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

# handler400 = 'core.views.bad_request'
handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    # path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

POST_REPR_MAX_CHARS: int = 30


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
        help_text='Введите название группы'
    )
    slug = models.SlugField(
        unique=True,
        max_length=200,
        verbose_name='Slug группы',
        help_text='Укажите адрес для страницы группы. Используйте только '
                  'латиницу, цифры, дефисы и знаки подчёркивания'
    )
    description = models.TextField(
        blank=True,
        null=True,
        verbose_name='Описание группы',
        help_text='Введите описание группы'
    )

    class Meta:
        db_table = 'groups'
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст записи'
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста',
        help_text='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу (не обязательно)'
    )
    image = models.ImageField(
        verbose_name='Изображение',
        help_text='Загрузите изображение (не обязательно)',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        db_table = 'posts'
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __repr__(self):
        return (
            f'Post id: {self.pk}, '
            f'Start text: {self.text[:POST_REPR_MAX_CHARS]}.....'
        )

    def __str__(self):
        return (
            f'{self.text[:POST_REPR_MAX_CHARS]}.....'
        )


class Comment(models.Model):
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
        help_text='Автор комментария'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментируемый пост',
        help_text='Пост, к которому оставлен комментарий'
    )

    class Meta:
        db_table = 'comments'
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __repr__(self):
        return (
            f'Comment id: {self.pk}, '
            f'Start text: {self.text[:POST_REPR_MAX_CHARS]}.....'
        )

    def __str__(self):
        return (
            f'{self.text[:POST_REPR_MAX_CHARS]}.....'
        )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Автор',
    )

    class Meta:
        db_table = 'follows'
        verbose_name = 'Подписки'
        verbose_name_plural = 'Подписки'
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'],
            name='unique_follow')
        ]

    def __repr__(self):
        return (
            f'Follow id: {self.pk}, '
            f'{self.user.username} >>> {self.author.username}'
        )

    def __str__(self):
        return f'{self.user.username} >>> {self.author.username}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        text = self.cleaned_data['text']

        if len(text) < 2:
            raise forms.ValidationError(
                'Текст сообщения должен содержать больше одного символа'
            )

        return text


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('text',)

    def clean_text(self):
        text = self.cleaned_data['text']

        if len(text) < 2:
            raise forms.ValidationError(
                'Текст комментария должен содержать больше одного символа'
            )

        return text

yatube/posts/views.py
# posts/views.py

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginator_


@cache_page(settings.CASHE_TIMEOUT, key_prefix='index_page')
def index(request):
    template = 'posts/index.html'
    posts_list = Post.objects.select_related(
        'author', 'group').all()
    page_obj = paginator_(request, posts_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    group_posts = group.posts.select_related(
        'author').all()
    page_obj = paginator_(request, group_posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    # follow_flag:
    # ( 0) - Подписки нет
    # ( 1) - Подписка существует
    # (-1) - Подписка не может существовать
    follow_flag = 0
    if request.user.is_authenticated:
        user = get_object_or_404(User, username=request.user.username)
        follow_obj = Follow.objects.filter(user=user, author=author)
        # Задача конструкции выпиливать кнопку подписки для самого себя
        if follow_obj.exists():
            follow_flag = 1
        elif author == user:
            follow_flag = -1
    author_posts = author.posts.select_related(
        'group').all()
    page_obj = paginator_(request, author_posts)

    context = {
        'author': author,
        'page_obj': page_obj,
        'follow_flag': follow_flag,
    }
    return render(request, template, context)


def post_detail(request, post_id):

    if request.method != 'GET' and request.method != 'POST':
        return HttpResponseNotAllowed()

    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.select_related('author')
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'comments': comments,
        'form': form
    }

    return render(request, template, context)


@login_required
def post_create(request):

    if request.method != 'GET' and request.method != 'POST':
        return HttpResponseNotAllowed()

    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    context = {'is_edit': False, 'form': form}

    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', request.user)

    return render(request, template, context)


@login_required
def post_edit(request, post_id):

    if request.method != 'GET' and request.method != 'POST':
        return HttpResponseNotAllowed(('GET', 'POST'))

    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id)

    if request.user != post.author:
        return redirect('posts:post_detail', post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    context = {'is_edit': True, 'form': form}

    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)

    return render(request, template, context)


@login_required
def add_comment(request, post_id):

    if request.method != 'GET' and request.method != 'POST':
        return HttpResponseNotAllowed(('GET', 'POST'))

    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    user = get_object_or_404(User, username=request.user.username)
    post_list = Post.objects.filter(author__following__user=user)
    page_obj = paginator_(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = get_object_or_404(User, username=request.user.username)
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    # follow_obj = Follow.objects.filter(user=user, author=author)
    # can_follow = not follow_obj.exists() and user != author
    # if can_follow:
    #     Follow.objects.create(user=user, author=author)
    return redirect('posts:profile', username=author.username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    user = get_object_or_404(User, username=request.user.username)
    follow_obj = Follow.objects.filter(user=user, author=author)
    follow_obj.delete()
    return redirect('posts:profile', username=author.username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}
{% if is_edit %}
Редактировать запись
{% else %}
Добавить запись
{% endif %}
{% endblock title %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% if is_edit %}
        Редактировать запись
        {% else %}
        Добавить запись
        {% endif %}
      </div>
      <div class="card-body">
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endif %}
        <form method="post"
        {% if is_edit %}
        action="{% url 'posts:post_edit' form.instance.id %}"
        {% else %}
        action="{% url 'posts:post_create' %}"
        {% endif %}
        enctype="multipart/form-data"
        >
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>
              {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
          {% endfor %}
          <div class="col-md-1 mx-auto">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
              Сохранить
              {% else %}
              Добавить
              {% endif %}
            </button>
          </div>
        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock content %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}
Записи избранных авторов
{% endblock title %}
{% block content %}
<div class="container py-5">
  {% include 'includes/switcher.html' %}
  <p><h1>Записи избранных авторов</h1></p>
  <br>
  <br>
  <br>
  {% for post in page_obj %}
    {% include 'includes/post_frame.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
Записи сообщества {{ group.title }}
{% endblock title %}
{% block content %}
<div class="container py-5">
  <p><h1>{{ group.title }}</h1></p>
  <p>{{ group.description }}</p>
  <br>
  {% for post in page_obj %}
    {% include 'includes/post_frame.html' %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock content %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}
Последние обновления на сайте
{% endblock title %}
{% block content %}
<div class="container py-5">
  {% include 'includes/switcher.html' %}
  <p><h1>Это главная страница проекта Yatube</h1></p>
  <br>
  {% for post in page_obj %}
    {% include 'includes/post_frame.html' %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}
Пост: {{ post }}
{% endblock title %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group }}
          <br>
          <a href="{% url 'posts:group_list' post.group.slug %}">
            Все записи группы
          </a>
        </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            Все посты пользователя
          </a>
        </li>
        {% if request.user == post.author %}
        <li class="list-group-item">
          <a href="{% url 'posts:post_edit' post.pk %}">Редактировать</a>
        </li>
        {% endif %}
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image '600x200' crop="center" upscale=True as img %}
      <img class="card-img my-2" src="{{ img.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.pk %}">
            {% csrf_token %}
            <div class="form-group mb-2">
              <textarea name="text" cols="40" rows="5" class="form-control" required id="id_text"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
      {% endif %}
      {% for comment in comments %}
      {% include 'includes/comment_frame.html' %}
      {% endfor %}
    </article>
  </div>
</div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
Профайл пользователя {{ author }}
{% endblock title %}
{% block content %}
<div class="container py-5">
  <div class="mb-5">
    <p><h1>Все посты пользователя {{ author.username }}</h1></p>
    <aside class="col-12 col-md-3 mb-2 mt-2 shadow-sm">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <h3>Автор: <b>{{ author.get_full_name }}</b></h3>
        </li>
        <li class="list-group-item">
          Всего постов: {{ author.posts.count }}
        </li>
        <li class="list-group-item">
          Всего подписок: {{ author.follower.count }}
        </li>
        <li class="list-group-item">
          Всего подписчиков: {{ author.following.count }}
        </li>
        <li class="list-group-item">
          
        </li>
      </ul>
    </aside>
      {% if follow_flag == 0 %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
      {% elif follow_flag == 1 %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
      {% comment %} Минутка юмора {% endcomment %}
      {% elif follow_flag == -1 %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'users:kmp' user.username %}" role="button"
      >
        Отписаться
      </a>
      {% endif %}

  </div>
  <br><br>
  {% for post in page_obj %}
    {% include 'includes/post_frame.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock content %}